carts/urls.py
from .views import *
from django.urls import re_path, path
from django.conf import settings

app_name='cart'

urlpatterns = [
    re_path(r'^$', cart_home, name='home'),
    re_path(r'^update/$', cart_update, name='update'),
    re_path(r'^checkout/$', checkout, name='checkout'),
    re_path(r'checkout/success/$', checkout_done, name='success')
]

products/urls.py
from .views import *
from django.urls import re_path, path
from django.conf import settings

app_name='products'

# unique product urls

urlpatterns = [
    re_path(r'^$', ProductListView.as_view(), name='list'),
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),
]

templates/base/css.html
{% load static %}
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

<link rel="stylesheet" href="{% static 'css/stripe-form.css' %}">
{#<link rel="stylesheet" href="{% static 'css/homepage.css' %}">#}
{#<link rel="stylesheet" href="{% static 'css/basestyles.css' %}">#}
<link rel="stylesheet" href="{% static 'css/products.css' %}">

templates/base/footer.html
<!-- Footer display -->

<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>© 2017-2018 Rocket Technology Inc.
    · 2222 Monroe St, Toledo, OH 43604
    · (419) 241-7777
    · <a href="#">Privacy</a>
    · <a href="#">Terms</a>
    </p>
</footer>

templates/base/forms.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto' style="margin-bottom: 40px;">
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button style="width:100%"type='submit' class='btn btn-primary'>Save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}
<script   src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous">
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<script src="https://js.stripe.com/v3/"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js"></script>

<script src="{% static 'js/application.js' %}"></script>
<script src="{% static 'js/csrf.ajax.js' %}"></script>
<script src="{% static 'js/billing.js' %}"></script>
{% include 'base/js_templates.html' %}

templates/base/js_templates.html
 {%verbatim %}
    <script id="stripeTemplate" type="text/x-jsrender">
        <form class='payment-form' action="" method="post" id="payment-form" data-token="{{:publish_key }}"
        data-next-url="{{:next_url}}">

          <div class="form-row">

            <div id="card-element" class="form-control">

            </div>

            <div id="card-errors" role="alert"></div>
          </div>

          <button class="btn btn-primary my-3 btn-load">{{:btnTitle}}</button>
        </form>
    </script>
 {% endverbatim %}

templates/base/navbar.html
<!-- Navbar -->

{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'services' as services_url %}
{% url 'products:list' as product_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{%  url 'cart:home' as cart_url %}
{% url  'settings' as settings_url %}

{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3 mx-auto fixed-top">

    {% if logo  %}
        <a href="{{home_url}}"><img style='height: 45px ; width:65px' src="{% static logo %}" /></a>
    {% endif %}

  <a style="color:yellow ; font-size:22px; font-weight: bold; font-family: 'Courier Times New Roman'" class="navbar-brand ml-4" href="#">
      {% if brandname %}
        {{ brandname }}
      {% else %}
        <h3>Rocket Tech</h3>
      {% endif %}
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active {% if request.path == home_url %}active {% endif %}" >
        <a class="nav-link" href="{{ home_url }}"><i class="fa fa-home"></i> Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item {% if request.path == contact_url %}active {% endif %}">
        <a class="nav-link" href="{{ contact_url }}"><i class="fa fa-envelope-open"></i> Contact </a>
      </li>

        <li class="nav-item {% if request.path == about_url %}active {% endif %}">
        <a class="nav-link" href="{{ services_url }}"><i class="fa fa-wrench"></i> Services </a>
      </li>

      <li class="nav-item {% if request.path == product_url %}active {% endif %}">
        <a class="nav-link" href="{{ product_url }}"> <i class="fa fa-laptop"></i> Products </a>
      </li>

        <li class="nav-item {% if request.path == product_url %}active {% endif %}">
        <a class="nav-link" href="{{ settings_url }}"><i class="fa fa-cogs"></i> Settings </a>
      </li>

    {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url_url %}active {% endif %}" >
            <a class="nav-link" href="{{ logout_url}}"><i class="fa fa-sign-out"></i> LogOut </a>
        </li>
    {% else %}
        <li class="nav-item {% if request.path == register_url %}active {% endif %}">
            <a class="nav-link" href="{{ register_url }}"><i class="fa fa-user-plus"></i> Sign Up </a>
        </li>
        <li class="nav-item {% if request.path == login_url %}active {% endif %}">
            <a class="nav-link" href="{{ login_url }}"><i class="fa fa-sign-in"></i> LogIn </a>
        </li>
    {% endif %}

      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class='navbar-cart-count'>{{ request.session.cart_items }}</span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>

   </ul>

   {% include 'snippets/search_form.html' %}

  </div>
</nav>