carts/urls.py
from .views import *
from django.urls import re_path, path
from django.conf import settings

app_name='cart'

urlpatterns = [
    re_path(r'^$', cart_home, name='home'),
    re_path(r'^update/$', cart_update, name='update'),
    re_path(r'^checkout/$', checkout, name='checkout'),
    re_path(r'checkout/success/$', checkout_done, name='success')
]

products/urls.py
from .views import *
from django.urls import re_path, path
from django.conf import settings

app_name='products'

# unique product urls

urlpatterns = [
    re_path(r'^$', ProductListView.as_view(), name='list'),
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),
]

products/models.py
from django.db import models
import random
import os
from django.db.models.signals import pre_save
from WebApplication.utils import unique_slug_generator
from django.urls import reverse
from django.db.models import Q


# get url of product image
def upload_image_path(instance, filename):
    print(instance)
    print(filename)
    location = 'media/'
    basename = os.path.basename(filename)
    name, ext = os.path.splitext(basename)
    filename = name[:12] + str(random.randint(1,100000000))  +  ext
    return location + '/' + filename


# methods to help query products

class ProductQuerySet(models.query.QuerySet):
    def featured(self):
        return self.filter(featured=True, active=True)

    def active(self):
        return self.filter(active=True)

    def search(self, query):
        query_lookup = Q(title__icontains=query) \
                       | Q(description1__icontains=query) \
                        | Q(description2__icontains=query) \
                       | Q(price__icontains=query) \
                       | Q(producttag__title__icontains=query)

        return self.filter(query_lookup).distinct()


# methods to return certain set of products or product by id or search for specif product

class ProductManager(models.Manager):
    def get_queryset(self):
        return  ProductQuerySet(self.model, using=self._db)

    def features(self):
        return self.get_queryset().featured()

    def all(self):
        return self.get_queryset().active()

    def get_by_id(self, id):
        query =  self.get_queryset().filter(id=id)

        if query.count() == 1:
            return query.first()

        return None

    def search(self, query):
        return self.get_queryset().search(query)

# Product Model

class Product(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(default='abc', blank=True, unique=True)
    description1 = models.CharField(max_length=400)
    description2 = models.CharField(max_length=400)
    price = models.DecimalField(decimal_places=2 , max_digits=10, default=39.99)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)


    objects = ProductManager()

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug':self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

# add unique slug for product when product is added

def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

products/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Product
from django.http import Http404
from carts.models import Cart
from analytics.signals import object_viewed_signal
from analytics.mixins import ObjectViewMixin
# Create your views here.


# controller for product detail page
class ProductDetailView(ObjectViewMixin,DetailView):
    # set page parameters
    model=Product
    queryset = Product.objects.all()
    template_name = 'products/detail.html'

    # set page context

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        cart, new_cart = Cart.objects.new_or_get(self.request)
        context['cart'] = cart
        return context

    # get product that details are shown for

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')

        try:
            product = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Product Not Found")
        except Product.MultipleObjectsReturned:
            query = Product.objects.filter(slug=slug, active=True)
            product= query.first()
        except:
            raise Http404("Cannot Find Product")

        #object_viewed_signal.send(product.__class__, instance=product, request=request)
        return product


#  Controller for product list page

class ProductListView( ListView):
    # set page parameters

    template_name = 'products/list.html'

    # get all products

    def get_queryset(self):
        request = self.request
        return Product.objects.all()

    # set page context

    def get_context_data(self, *args ,**kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        cart, new_cart = Cart.objects.new_or_get(self.request)
        context['cart'] = cart
        return context


#
# class ProductFeaturedListView(ObjectViewedMixin, ListView):
#     template_name = "products/list.html"
#
#     def get_queryset(self):
#         request = self.request
#         return Product.objects.all().featured()
#
# class ProductFeaturedDetailView(DetailView):
#     queryset = Product.objects.all().featured()
#     template_name = 'products/detail.html'

products/templates/products/snippets/card.html
<!-- Template For Product Display -->

<div class="card" style="margin-top: 20px;">
  {% if item.image %}
     <a href="{{ item.get_absolute_url }}">
        <img class="card-img-top" style="height:250px;width:300px ; margin-left:35px; margin-top:12px;" src="{{ item.image.url }}" alt="Card image cap">
     </a>
  {% endif %}
    <div class="card-body">
        <h2 style="text-align: center; "class="card-title">{{ item.title| upper }}</h2>
        <p class="card-text">{{ item.description1 | linebreaks |truncatewords:20 }}</p>
        <a style="width:100%" href="{{ item.get_absolute_url }}" class="btn btn-primary">Find Out More</a>
        <div style="width:100%;margin-top:7px;">
            {% include 'products/snippets/update_cart.html' with product=item cart=cart %}
        </div>
    </div>
</div>

products/templates/products/snippets/update_cart.html
 <!-- Display buttons to add or remove product from cart  -->

<form style="display:inline"  class='product-add-form' data-endpoint='{% url "cart:update"%}' method="post" action="{% url 'cart:update' %}" class="form">
    {% csrf_token %}

    <input type="hidden" name="product" value="{{ product.id }}">


        <span class="submit-span">
            {% if object in cart.products.all %}
                 In Cart <button style="width:100%;margin-top:7px;" type='submit' class="btn btn-danger">Remove?</button>
            {% else %}
                 <button style="width:100%;margin-top:7px;" type='submit' class="btn btn-success btn-block">Add To Cart</button>
            {% endif %}
        </span>

 </form>