carts/urls.py
from .views import *
from django.urls import re_path, path
from django.conf import settings

app_name='cart'

urlpatterns = [
    re_path(r'^$', cart_home, name='home'),
    re_path(r'^update/$', cart_update, name='update'),
    re_path(r'^checkout/$', checkout, name='checkout'),
    re_path(r'checkout/success/$', checkout_done, name='success')
]

search/urls.py
from .views import *
from django.urls import re_path, path
from django.conf import settings

app_name='search'

urlpatterns = [
    re_path(r'^$', SearchProductView.as_view(), name='query'),

]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from products.models import  Product
from django.views.generic import ListView
from django.db.models import Q


# Controller for product search
class SearchProductView(ListView):

    # set parameters
    template_name = 'search/view.html'

    # set context
    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductView, self).get_context_data(*args, **kwargs)
        context['query'] = self.request.GET.get('q')
        return context

    # query all products for searched for product

    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q')

        if query is not None:
            return Product.objects.search(query)

        return  Product.objects.none()

search/templates/snippets/search_form.html
<!-- Form to search products -->

<form class='search-form form-inline my-2 my-lg-0' method="get" action="{% url 'search:query' %}">
     <div class="input-group">
         <input class="form-control" name='q' type="search" value='{{ request.GET.q }}' placeholder="Search" aria-label="Search">
     <span class="input-group-btn">
         <button style="color:yellow" class="btn btn-outline-success" type="submit">Search</button>
     </span>
     </div>

 </form>